
DELETE {
    ?aas aasdata:dataSpecification ?ds .
    ?ds a aas:Reference ;
        aasref:key ?key ;
        a owl:NamedIndividual .
    ?key a aas:Key ;
        aaskey:value ?val ;
        aaskey:type ?type ;
        aaskey:idType ?idType ;
        a owl:NamedIndividual .
}
INSERT {
    aasdata:semanticIdValue a owl:DatatypeProperty .
    ?aas aasdata:semanticIdValue ?val .
}
WHERE {
    ?aas a aas:AssetAdministrationShell ;
        aasdata:dataSpecification ?ds .
    ?ds a aas:Reference ;
        aasref:key ?key .
    ?key a aas:Key ;
        aaskey:value ?val .
}
