PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX aasrange: <https://admin-shell.io/aas/3/0/RC01/Range/>

DELETE {
    ?prop aasrange:min ?min ; 
        aasrange:max ?max ; 
        aasrange:valueType ?valtype .
}
INSERT {
    ?prop aasrange:min ?propermin . 
    ?prop aasrange:max ?propermax . 
}
WHERE {
    ?prop aasrange:min ?min ; 
        aasrange:max ?max ; 
        aasrange:valueType ?valtype .
    FILTER (?valtype = "integer")
    BIND(STRDT(STR(?min), xsd:integer) AS ?propermin)
    BIND(STRDT(STR(?max), xsd:integer) AS ?propermax)
}
