PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX aasprop: <https://admin-shell.io/aas/3/0/RC01/Property/>

DELETE {
    ?prop aasprop:value ?val ; 
        aasprop:valueType ?valtype .
}
INSERT {
    ?prop aasprop:value ?properval . 
}
WHERE {
    ?prop aasprop:value ?val ; 
        aasprop:valueType ?valtype .
    FILTER (?valtype = "string")
    BIND(STRDT(STR(?val), xsd:string) AS ?properval)
}
