
DELETE {
    ?aas aasaas:submodel ?ref .
    ?ref a aas:Reference ;
        aasref:key ?key ;
        a owl:NamedIndividual .
    ?key a aas:Key ;
        aaskey:value ?val ;
        a owl:NamedIndividual .
    ?sm aasida:identification ?id .
    ?id a aas:Identifier ;
        a owl:NamedIndividual ;
        aaside:identifier ?idval ;
        aaside:idType ?idtval .
}
INSERT {
    ?aas aasaas:submodel ?sm .
}
WHERE {
    ?aas a aas:AssetAdministrationShell ;
        aasaas:submodel ?ref .
    ?ref a aas:Reference ;
        aasref:key ?key .
    ?key a aas:Key ;
        aaskey:value ?val .
    ?sm a aas:Submodel ;
        aasida:identification ?id .
    ?id aaside:identifier ?idval ;
        aaside:idType ?idtval .
    ?sm a aas:Submodel .
    FILTER (STR(?sm) = ?val)
}
