
DELETE {
    ?rel ?ordinal ?ref .
    ?ref a aas:Reference ;
        aasref:key ?key ;
        a owl:NamedIndividual .
    ?key a aas:Key ;
        aaskey:value ?val ;
        aaskey:type ?type ;
        a owl:NamedIndividual .
}
INSERT {
    ?rel ?ordinal ?aas .
}
WHERE {
    ?rel a aas:RelationshipElement ;
        ?ordinal ?ref .
    ?ref a aas:Reference ;
        aasref:key ?key .
    ?key a aas:Key ;
        aaskey:value ?val ;
        aaskey:type aaskeyelem:ASSETADMINISTRATIONSHELL .
    ?aas a aas:AssetAdministrationShell .
    FILTER (STR(?aas) = ?val)
}
