
DELETE {
    ?rel ?ordinal ?ref .
    ?ref a aas:Reference ;
        aasref:key ?key ;
        a owl:NamedIndividual .
    ?key a aas:Key ;
        aaskey:value ?val ;
        aaskey:type ?type ;
        a owl:NamedIndividual .
}
INSERT {
    ?value a owl:DatatypeProperty .
    ?rel ?value ?val .
}
WHERE {
    ?rel a aas:RelationshipElement ;
        ?ordinal ?ref .
    ?ref a aas:Reference ;
        aasref:key ?key .
    ?key a aas:Key ;
        aaskey:value ?val ;
        aaskey:type aaskeyelem:GLOBALREFERENCE .
}
