
DELETE {
    ?attr aassem:semanticId ?id .
    ?id a aas:Reference ;
        aasref:key ?key ;
        a owl:NamedIndividual .
    ?key a aas:Key ;
        aaskey:value ?val ;
        aaskey:type ?type ;
        a owl:NamedIndividual .
}
INSERT {
    aassem:semanticIdValue a owl:DatatypeProperty .
    ?attr aassem:semanticIdValue ?val .
}
WHERE {
    {
        ?attr a aas:Property .
    } UNION {
        ?attr a aas:Range .
    }
    ?attr aassem:semanticId ?id .
    ?id a aas:Reference ;
        aasref:key ?key .
    ?key a aas:Key ;
        aaskey:value ?val .
}
